### ISSUE TITLE
Vehicles not spawning, assets on buildings flashing on save startup

### ISSUE THREAD

**Issue by henryheyhey123** [klyte45/WriteTheSignsFiles#1]
Hi Klyte, great fan of your work :) on starting my save game after installing your mod I get various lighting glitches, flashing of fan units etc. on top of buildings, and finally no traffic spawning. It is heavily modded but seems to be about a StartStopLocation call by the Klyte Commons library. If you could have a look I would be very grateful!

My output log and mods can be accessed below:
[mods from compat checker.log](https://github.com/klyte45/WriteTheSignsFiles/files/4851493/mods.from.compat.checker.log)
[output_log_30_6_20.txt](https://drive.google.com/file/d/1pQZ6eC2quPcSHZPW0GnkYFmM19lSRB8c/view?usp=sharing)

**Comment by klyte45** [comment]
About the traffic problem: I'm almost sure it's related to TLM with Service Vehicle Selector on same savegame, both are incompatible...

About the map stop points, I would ask you to turn on the debug mod of WTS and then play a little to generate some log to me analyze. I'm almost sure that a corrupted/incomplete network in a building but I need to get more information.

**Comment by henryheyhey123** [comment]
Disabling SVS didn't seem to make a difference. It only seems to be when I install WTS on top of my current mods.

Here's what it looks like
![46suya](https://user-images.githubusercontent.com/5504822/86130545-369c3600-badc-11ea-8af7-8490f09a7fd4.gif)

Also, here's the output log with the debug mode turned on:
[output_log_30_6_20_2.txt](https://drive.google.com/file/d/1CJdE36BnZVrW9L9qND6pcLpZgc82BRJu/view?usp=sharing)

**Comment by klyte45** [comment]
Is this still happening in current version?

**Comment by henryheyhey123** [comment]
Hey Klyte, it seems like its been fixed in the latest version.  Cheers! From: Leandro KlyteSent: 12 March 2021 16:02To: klyte45/WriteTheSignsFilesCc: Henry W; AuthorSubject: Re: [klyte45/WriteTheSignsFiles] Vehicles not spawning, assets on buildings flashing on save startup (#1) Is this still happening in current version?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
